language: swift
osx_image: xcode9.2

cache:
  - cocoapods
  - bundler

before_install:
  - pod install --repo-update
  - brew update
  - brew install swiftlint || true

before_script:
  - bundle exec danger

script:
  - set -o pipefail
  - xcodebuild clean test -workspace TrustCore.xcworkspace -scheme "TrustCore" -destination 'platform=iOS Simulator,name=iPhone 8'
  - xcodebuild clean test -workspace TrustCore.xcworkspace -scheme "TrustCore" -destination 'platform=iOS Simulator,name=iPhone 5'

after_success:
  - bash <(curl -s https://codecov.io/bash)
